### PR TITLE
Update to work with latest Slack classes and DOM structure

### LINKED ISSUE #5: Does this still work? Nothing happening
Does this extension still work? I'm seeing nothing happening in Chrome on OS X.

### PR DESCRIPTION
**Pull request by JeremyPlease**
Thanks for building this in the first place! I was able to make a quick fix to get it working again. I tested this against current Slack site and confirmed that it works.

This fixes #5.

### CODE REVIEW

**Comment by gunar** [comment]
Thanks!!

**Comment by gunar** [comment]
Published to chrome webstore

**Comment by gunar** [comment]
@JeremyPlease, consider joining ~my~ our startup!

here are some links which you might find helpful

https://medium.com/invisible-hiring/dont-work-with-us-7dd6ca044d32

https://invisible-technologies.breezy.hr/p/400dab168b95-senior-software-engineer

Thanks!

**Comment by JeremyPlease** [comment]
@gunar Happy to help! 😃 
And thanks for the invite. I'll keep Invisible Technologies in mind if my work situation ever changes.

**Pull request merged**
